spring:
  name: demo-local
  datasource:
    platform: mysql
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: root


    driver-class: com.mysql.cj.jdbc.Driver
    hikari:
      minimumIdle: 5
      maximumIdle: 20
      idleTimeout: 2000
      connectionTimeout: 2000
      poolName: demo-pool-local
      maxLifetime: 30000
    jpa:
      hibernate:
       ddl-auto: update
      genrate-ddl: false
      show-sql: false
      show_sql: true
      properties:
        hibernate:
          show-sql: false
          format_sql: true
          dialect: org.hibernate.dialect.MySQL8Dialect
    web:
      resources:
        static-locations: file:./storage/
server:
  servlet:
    context-path: /demo-api-local
  port: 1002

logging:
  file.name: logs/demo.log
  pattern:
    console: "%d %-5level [%thread] %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: INFO
    org.hibernate: INFO
    com.amstech.tripplanner.booking: INFO

app:
  max-file-size: 5000000	
